site_name: Pythonキホンのキホンのキホン
theme:
  name: material
  features:
  #   - toc.integrate
  #   - navigation.top
   - navigation.expand
  #   - navigation.indexes
# extra_css:
#   - style.css
markdown_extensions:
  - pymdownx.highlight:
  - admonition
  - def_list
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# sync_main_only: true

nav:
  - トップページ: index.md
  - 教科書:
    - 教科書トップページ: 01_textbook/index.md
    - 01_プログラミングとは:
      - プログラミングとは: 01_textbook/01_pgintro/index.md
      - プログラムの流れ: 01_textbook/01_pgintro/program_flow.md
      - 真偽値: 01_textbook/01_pgintro/boolean_value.md
      - 条件分岐のバリエーション: 01_textbook/01_pgintro/conditional_branch_variations.md
      - フラグとは: 01_textbook/01_pgintro/flag.md
    - 02_Pythonとは:
      - Pythonとは: 01_textbook/02_pyintro/index.md
    - 03_Pythonの基本:
      - Pythonの基本: 01_textbook/03_pgbasic/index.md
      - 関数とは: 01_textbook/03_pgbasic/what_function.md
      - print関数: 01_textbook/03_pgbasic/print_function.md
      - print関数で改行しない方法: 01_textbook/03_pgbasic/print_function_without_newline.md
      - コメントとは: 01_textbook/03_pgbasic/comment.md
      - Pythonでプログラムを書くときのルール: 01_textbook/03_pgbasic/rule.md
      - 四則演算子について学ぼう: 01_textbook/03_pgbasic/four_arithmetic_operations.md
      - ブロックとインデント: 01_textbook/03_pgbasic/block_and_indent.md
    - 04_基本文法:
      - 基本文法: 01_textbook/04_basic/index.md
      - エラーについて学ぼう: 01_textbook/04_basic/about_error.md
      - 初心者のルール違反あるある: 01_textbook/04_basic/beginners_rule_violations.md
    - 05_変数とデータ型:
      - 変数とデータ型: 01_textbook/05_variables/index.md
      - 文字列型: 01_textbook/05_variables/string.md
      - 変数と代入について学ぼう: 01_textbook/05_variables/variables_and_assignment.md
    - 06_文字列操作:
      - 文字列操作: 01_textbook/06_string/index.md
      - 文字列に変数を埋め込む方法を学ぼう: 01_textbook/06_string/formatted_string.md
      - 文字列を置換するreplaceメソッドを学ぼう: 01_textbook/06_string/replace_method.md
    - 07_演算子:
      - 演算子: 01_textbook/07_operator/index.md
      - 比較演算子: 01_textbook/07_operator/comparison_operator.md
      - 条件式: 01_textbook/07_operator/conditional_expression.md
      - 条件式と真偽値: 01_textbook/07_operator/conditional_expression_and_boolean_value.md
    - 08_リスト型操作:
      - リスト型操作: 01_textbook/08_list/index.md
    - 09_タプル型操作:
      - タプル型操作: 01_textbook/09_tuple/index.md
    - 10_辞書型操作:
      - 辞書型操作: 01_textbook/10_dictionary/index.md
    - 11_集合型操作:
      - 集合型操作: 01_textbook/11_set/index.md
    - 12_条件分岐:
      - 条件分岐: 01_textbook/12_condition/index.md
      - if文（満たすときだけ処理）: 01_textbook/12_condition/if_branch.md
      - if文（満たさない場合も処理）: 01_textbook/12_condition/if_else_branch.md
      - if文（３段以上に分岐させる）: 01_textbook/12_condition/if_elif_else_branch.md
      - if文のエラーあるある: 01_textbook/12_condition/common_errors_with_if_statements.md
    - 13_繰り返し処理:
      - 繰り返し処理: 01_textbook/13_iterating/index.md
    - 14_ファイル・フォルダ操作:
      - ファイル・フォルダ操作: 01_textbook/14_files/index.md
    - 15_日付時刻操作:
      - 日付時刻操作: 01_textbook/15_datetime/index.md
    - 16_構文エラー:
      - 構文エラー: 01_textbook/16_serror/index.md
    - 17_実行時エラー:
      - 実行時エラー: 01_textbook/17_rerror/index.md
    - 18_組込み関数:
      - 組込み関数: 01_textbook/18_functions/index.md
    - 19_標準ライブラリ:
      - 標準ライブラリ: 01_textbook/19_libraries/index.md
    - 20_オブジェクト指向（クラス・インスタンス）:
      - オブジェクト指向（クラス・インスタンス）: 01_textbook/20_oo/index.md
    - 21_例外処理:
      - 例外処理: 01_textbook/21_exception/index.md
    - 22_内包表記:
      - 内包表記: 01_textbook/22_comprehensions/index.md
    - 23_ラムダ式（無名関数）:
      - ラムダ式: 01_textbook/23_lambda/index.md
    - 24_正規表現:
      - 正規表現: 01_textbook/24_re/index.md

  - ミッション:
    - はじめに: 02_missions/index.md
    - 第2ミッション:
      - アジェンダ: 02_missions/02_mission/index.md
      - ミッション: 02_missions/02_mission/mission.md
      - デモ: 02_missions/02_mission/demo_01.md
      - レッスン:
        - 関数とは: 01_textbook/03_pgbasic/what_function.md
        - print関数: 01_textbook/03_pgbasic/print_function.md
        - 文字列型: 01_textbook/05_variables/string.md
        - コメントとは: 01_textbook/03_pgbasic/comment.md
        - Pythonでプログラムを書くときのルール: 01_textbook/03_pgbasic/rule.md
      - トライ: 02_missions/02_mission/try_01.md
      - グッジョブ: 02_missions/02_mission/good_job.md
    - 第3ミッション:
      - アジェンダ: 02_missions/03_mission/index.md
      - ミッション: 02_missions/03_mission/mission.md
      - デモ: 02_missions/03_mission/demo_01.md
      - レッスン:
        - エラーについて学ぼう: 01_textbook/04_basic/about_error.md
        - 初心者のルール違反あるある: 01_textbook/04_basic/beginners_rule_violations.md
      - トライ: 02_missions/03_mission/try_01.md
      - グッジョブ: 02_missions/03_mission/good_job.md
    - 第4ミッション:
      - アジェンダ: 02_missions/04_mission/index.md
      - ミッション: 02_missions/04_mission/mission.md
      - デモ（1）: 02_missions/04_mission/demo_01.md
      - レッスン:
        - 四則演算子について学ぼう: 01_textbook/03_pgbasic/four_arithmetic_operations.md
      - トライ（1）: 02_missions/04_mission/try_01.md
      - デモ（2）: 02_missions/04_mission/demo_02.md
      - レッスン:
        - 変数と代入について学ぼう: 01_textbook/05_variables/variables_and_assignment.md
      - トライ（2）: 02_missions/04_mission/try_02.md
      - デモ（3）: 02_missions/04_mission/demo_03.md
      - レッスン:
        - 文字列に変数を埋め込む方法を学ぼう: 01_textbook/06_string/formatted_string.md
      - トライ（3）: 02_missions/04_mission/try_03.md
      - デモ（4）: 02_missions/04_mission/demo_04.md
      - レッスン:
        - 変数を使って四則演算の結果を表示する方法を学ぼう: 02_missions/04_mission/lesson_01.md
      - トライ（4）: 02_missions/04_mission/try_04.md
      - グッジョブ: 02_missions/04_mission/good_job.md
    - 第5ミッション:
      - アジェンダ: 02_missions/05_mission/index.md
      - ミッション: 02_missions/05_mission/mission.md
      - デモ（1）: 02_missions/05_mission/demo_01.md
      - レッスン:
        - 文字列を置換するreplaceメソッドを学ぼう: 01_textbook/06_string/replace_method.md
      - トライ（1）: 02_missions/05_mission/try_01.md
      - デモ（2）: 02_missions/05_mission/demo_02.md
      - レッスン:
        - 指定した文字列を一括置換する方法について学ぼう: 02_missions/05_mission/lesson_01.md
      - トライ（2）: 02_missions/05_mission/try_02.md
      - グッジョブ: 02_missions/05_mission/good_job.md
    - 第6ミッション:
      - アジェンダ: 02_missions/06_mission/index.md
      - ミッション: 02_missions/06_mission/mission.md
      - デモ（1）: 02_missions/06_mission/demo_01.md
      - レッスン:
        - 今日の日付を取得する方法を学ぼう: 01_textbook/15_datetime/today.md
      - トライ（1）: 02_missions/06_mission/try_01.md
      - デモ（2）: 02_missions/06_mission/demo_02.md
      - レッスン:
        - 日付の引き算をする方法を学ぼう: 01_textbook/15_datetime/difference.md
      - トライ（2）: 02_missions/06_mission/try_02.md
      - デモ（3）: 02_missions/06_mission/demo_03.md
      - レッスン:
        - 今日が生まれてから何日目か表示する方法について学ぼう: 02_missions/06_mission/lesson_01.md
      - トライ（）: 02_missions/06_mission/try_03.md
      - グッジョブ: 02_missions/06_mission/good_job.md
    - 第7ミッション:
      - アジェンダ: 02_missions/07_mission/index.md
      - ミッション: 02_missions/07_mission/mission.md
      - デモ（1）: 02_missions/07_mission/demo_01.md
      - レッスン:
        - 奇数偶数の判定方法を学ぼう: 02_missions/07_mission/lesson_01.md
        - プログラムの流れ: 01_textbook/01_pgintro/program_flow.md
        - 条件分岐のバリエーション: 01_textbook/01_pgintro/conditional_branch_variations.md
        - if文（満たすときだけ処理）: 01_textbook/12_condition/if_branch.md
        - if文（満たさない場合も処理）: 01_textbook/12_condition/if_else_branch.md
        - ブロックとインデント: 01_textbook/03_pgbasic/block_and_indent.md
        - 条件式: 01_textbook/07_operator/conditional_expression.md
        - 比較演算子: 01_textbook/07_operator/comparison_operator.md
        - 真偽値: 01_textbook/01_pgintro/boolean_value.md
        - 条件式と真偽値: 01_textbook/07_operator/conditional_expression_and_boolean_value.md
        - if文のエラーあるある: 01_textbook/12_condition/common_errors_with_if_statements.md
      - トライ（1）: 02_missions/07_mission/try_01.md
      - デモ（2）: 02_missions/07_mission/demo_02.md
      - レッスン:
        - if文（３段以上に分岐させる）: 01_textbook/12_condition/if_elif_else_branch.md
      - トライ（2）: 02_missions/07_mission/try_02.md
      - デモ（3）: 02_missions/07_mission/demo_03.md
      - レッスン:
        - うるう年かそうでないか判定する方法を学ぼう（1）: 02_missions/07_mission/lesson_02.md
        - フラグとは: 01_textbook/01_pgintro/flag.md
        - print関数で改行しない方法: 01_textbook/03_pgbasic/print_function_without_newline.md
        - うるう年かそうでないか判定する方法を学ぼう（2）: 02_missions/07_mission/lesson_03.md
      - トライ（3）: 02_missions/07_mission/try_03.md
      - グッジョブ: 02_missions/07_mission/good_job.md

